"""add support tickets

Revision ID: 20260301_000001
Revises: 20260226_000009
Create Date: 2026-03-01 08:30:00.000000+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "20260301_000001"
down_revision: Union[str, None] = "20260226_000009"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "monitor_support_tickets",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("tg_user_id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=255), nullable=True),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=True),
        sa.Column("responded_by_tg_id", sa.BigInteger(), nullable=True),
        sa.Column("responded_at", sa.DateTime(), nullable=True),
        sa.Column("admin_notified", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["monitor_users.id"],
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_monitor_support_tickets_created_at"),
        "monitor_support_tickets",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_support_tickets_status"),
        "monitor_support_tickets",
        ["status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_support_tickets_tg_user_id"),
        "monitor_support_tickets",
        ["tg_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_monitor_support_tickets_user_id"),
        "monitor_support_tickets",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_monitor_support_tickets_user_id"),
        table_name="monitor_support_tickets",
    )
    op.drop_index(
        op.f("ix_monitor_support_tickets_tg_user_id"),
        table_name="monitor_support_tickets",
    )
    op.drop_index(
        op.f("ix_monitor_support_tickets_status"),
        table_name="monitor_support_tickets",
    )
    op.drop_index(
        op.f("ix_monitor_support_tickets_created_at"),
        table_name="monitor_support_tickets",
    )
    op.drop_table("monitor_support_tickets")
    # ### end Alembic commands ###
